### ISSUE TITLE
It's asking for consumer rights and I can't find it.

### ISSUE THREAD

**Issue by saifete11ruet** [microsoftgraph/msgraph-sample-nodeexpressapp#152]
We're unable to complete your request
unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.

**Comment by jasonjoh** [comment]
Make sure your app registration allows personal accounts (also known as consumer accounts):

> Set Supported account types to **Accounts in any organizational directory and personal Microsoft accounts**.
